# Security posture: supporting PRs in staging requires running and deploying untrusted code.
# However, by limiting deployments to the `/staging` subdirectory via this workflow,
# we minimize the potential attack surface to a known subset of pages.

name: 'Deploy PR to composite target for staging'
run-name: 'Deploy PR to composite target for staging'

on:
  workflow_run:
    workflows: [Build PR for staging]
    types:
      - completed

permissions:
  artifact-metadata: write
  contents: read
  pull-requests: write

env:
  TARGET_REPO: ${{ vars.COMPOSITE_TARGET_REPO }}

concurrency:
  group: ci-ngiab-website-pr-deploy-${{ github.event.workflow_run.id }}
  cancel-in-progress: false

jobs:
  pr-deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Download PR CD payload
        uses: actions/download-artifact@v8
        with:
          name: pr-cd-payload
          path: ${{ runner.temp }}/
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Unpack payload inputs
        id: extract-json
        run: |
          payload=$(cat "${{ runner.temp }}/pr_cd_payload.json")
          echo "payload_json=$payload" >> "$GITHUB_OUTPUT"
          echo "$payload"
      
      - name: Parse payload inputs
        id: parse-json
        env:
          TEMP_NUM: ${{ fromJson(steps.extract-json.outputs.payload_json).pr_number }}
          TEMP_ID: ${{ fromJson(steps.extract-json.outputs.payload_json).build_id }}
          TEMP_SN: ${{ fromJson(steps.extract-json.outputs.payload_json).should_notify }}
        run: |
          {
            echo "PR_NUMBER=$TEMP_NUM"
            echo "BUILD_ID=$TEMP_ID"
            echo "SHOULD_NOTIFY=$TEMP_SN"
          } >> "$GITHUB_ENV"

      - name: Verify and set target path
        run: |
          INT_REGEX='^[0-9]+$'
          if [[ ! "$PR_NUMBER" =~ $INT_REGEX ]]; then
            echo "Provided PR number '${PR_NUMBER}' is not a valid integer. Aborting." >> "$GITHUB_STEP_SUMMARY"
            exit 1
          elif [[ ! "$BUILD_ID" =~ $INT_REGEX ]]; then
            echo "Provided build id '${BUILD_ID}' is not a valid integer. Aborting." >> "$GITHUB_STEP_SUMMARY"
            exit 1
          fi
          echo "TARGET_PATH=staging/$PR_NUMBER" >> "$GITHUB_ENV"

      - name: Download build artifact
        uses: actions/download-artifact@v8
        with:
          artifact-ids: ${{ env.BUILD_ID }}
          run-id: ${{ github.event.workflow_run.id }}
          path: build/
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to composite repository
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: "build/"
          ssh-key: ${{ secrets.SSH_DEPLOY_NGIAB_SUBDOMAIN }}
          repository-name: ${{ env.TARGET_REPO }}
          target-folder: ${{ env.TARGET_PATH }}
          clean: true # Set to false if deploying to a composite repository's root!
          git-config-name: "github-actions"
          git-config-email: "github-actions@github.com"
      
      - name: Comment PR with staging link
        uses: mshick/add-pr-comment@v2
        if: ${{ vars.SILENCE_COMPOSITE_PR_MESSAGE != 'true' && env.SHOULD_NOTIFY == 'true' }}
        with:
          message: |
            **Staging Preview:**
            🚀 https://ngiab.ciroh.org/${{ env.TARGET_PATH }}
            
            _Built from commit ${{ github.sha }}_
